line-length = 100
target-version = "py312"
exclude = [".venv", "build", "dist"]

select = [
  "E",
  "F",
  "B",
  "I",
  "UP",
  "C90",
  "SIM",
  "PL",
]

ignore = [
  "E501",
  "PLR2004",
  "B008",
]
